var origCharacters = [
  {
    'name': 'Alex',
    'imageFile': 'Alex.png',
    'gender': 'male',
    'hairColor': 'black',
    'dressColor': 'blue',
    'facialHair': true,
    'mushtache': true,
    'beard': false,
    'glasses': false,
    'earRings': false,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'Max',
    'imageFile': 'Max.png',
    'gender': 'male',
    'hairColor': 'black',
    'dressColor': 'red',
    'facialHair': true,
    'mushtache': true,
    'beard': false,
    'glasses': false,
    'earRings': false,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'Anne',
    'imageFile': 'Anne.png',
    'gender': 'female',
    'hairColor': 'black',
    'dressColor': 'red',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': true,
    'earRings': false,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'Claire',
    'imageFile': 'Claire.png',
    'gender': 'female',
    'hairColor': 'orange',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': false,
    'earRings': true,
    'baldness': false,
    'headgear': true,
  },
  {
    'name': 'Bernard',
    'imageFile': 'Bernard.png',
    'gender': 'male',
    'hairColor': 'grey',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': false,
    'earRings': false,
    'baldness': false,
    'headgear': true,
  },
  {
    'name': 'Bill',
    'imageFile': 'Bill.png',
    'gender': 'male',
    'hairColor': 'orange',
    'dressColor': 'blue',
    'facialHair': true,
    'mushtache': true,
    'beard': true,
    'glasses': false,
    'earRings': false,
    'baldness': true,
    'headgear': false,
  },
  {
    'name': 'Charles',
    'imageFile': 'Charles.png',
    'gender': 'male',
    'hairColor': 'blonde',
    'dressColor': 'red',
    'facialHair': true,
    'mushtache': true,
    'beard': false,
    'glasses': false,
    'earRings': false,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'David',
    'imageFile': 'David.png',
    'gender': 'male',
    'hairColor': 'grey',
    'dressColor': 'red',
    'facialHair': true,
    'mushtache': false,
    'beard': true,
    'glasses': false,
    'earRings': false,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'Eric',
    'imageFile': 'Eric.png',
    'gender': 'male',
    'hairColor': 'blonde',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': false,
    'earRings': true,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'George',
    'imageFile': 'George.png',
    'gender': 'male',
    'hairColor': 'grey',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': false,
    'earRings': false,
    'baldness': true,
    'headgear': false,
  },
  {
    'name': 'Alfred',
    'imageFile': 'Alfred.png',
    'gender': 'male',
    'hairColor': 'orange',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': true,
    'earRings': false,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'Susan',
    'imageFile': 'Susan.png',
    'gender': 'female',
    'hairColor': 'blonde',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': false,
    'earRings': true,
    'baldness': false,
    'headgear': true,
  },
  {
    'name': 'Herman',
    'imageFile': 'Herman.png',
    'gender': 'male',
    'hairColor': 'orange',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': false,
    'earRings': false,
    'baldness': true,
    'headgear': false,
  },
  {
    'name': 'Frans',
    'imageFile': 'Frans.png',
    'gender': 'male',
    'hairColor': 'orange',
    'dressColor': 'blue',
    'facialHair': true,
    'mushtache': true,
    'beard': true,
    'glasses': false,
    'earRings': false,
    'baldness': false,
    'headgear': true,
  },
  {
    'name': 'Maria',
    'imageFile': 'Maria.png',
    'gender': 'female',
    'hairColor': 'brown',
    'dressColor': 'red',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': false,
    'earRings': true,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'Robert',
    'imageFile': 'Robert.png',
    'gender': 'male',
    'hairColor': 'brown',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': true,
    'earRings': false,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'Sam',
    'imageFile': 'Sam.png',
    'gender': 'male',
    'hairColor': 'grey',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': true,
    'earRings': false,
    'baldness': false,
    'headgear': true,
  },
  {
    'name': 'Anita',
    'imageFile': 'Anita.png',
    'gender': 'female',
    'hairColor': 'blonde',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': false,
    'earRings': true,
    'baldness': false,
    'headgear': false,
  },
  {
    'name': 'Tom',
    'imageFile': 'Tom.png',
    'gender': 'male',
    'hairColor': 'black',
    'dressColor': 'blue',
    'facialHair': false,
    'mushtache': false,
    'beard': false,
    'glasses': true,
    'earRings': false,
    'baldness': false,
    'headgear': true,
  },
  {
    'name': 'Peter',
    'imageFile': 'Peter.png',
    'gender': 'male',
    'hairColor': 'grey',
    'dressColor': 'blue',
    'facialHair': true,
    'mushtache': true,
    'beard': true,
    'glasses': false,
    'earRings': false,
    'baldness': true,
    'headgear': false,
  },
];

List<Map<String, Object>> characters;